name: GitHub Copilot - ansökan
description: Ansök om tillgång till GitHub Copilot
title: "[Copilot] ansökan - <ditt namn>"
labels: ["copilot-request"]
assignees:
  - aikidokan
body:
  - type: input
    id: github_user_boss
    attributes:
      label: Din chefs e-postadress
      description: Ange din chefs e-postadress
      placeholder: namn@skogforsk.se
    validations:
      required: true
  - type: input
    id: github_username
    attributes:
      label: GitHub-användarnamn
      description: Ange ditt GitHub-användarnamn (t.ex. aikidokan)
      placeholder: aikidokan
    validations:
      required: true

  - type: input
    id: work_email
    attributes:
      label: Skogforsk e-postadress
      description: Ange din Skogforsk e-postadress (för verifiering)
      placeholder: namn@skogforsk.se
    validations:
      required: true

  - type: dropdown
    id: prior-experience
    attributes:
      label: Tidigare erfarenhet
      description: Har du tidigare erfarenhet av att använda GitHub Copilot?
      options:
        - Ja
        - Nej
      default: 1
    validations:
      required: true

  - type: textarea
    id: purpose
    attributes:
      label: Syfte
      description: Kort beskrivning av hur du kommer använda Copilot och vad du ser för möjligheter med det i ditt arbete.
      placeholder: T.ex. utveckling i .NET, Python, Azure automation...
      render: text
    validations:
      required: true
